### ISSUE TITLE
what is the meaning of bexpression in modsecurity_crs_41_xss_attacks.conf ?

### ISSUE THREAD

**Issue by chenyoufu** [SpiderLabs/owasp-modsecurity-crs#228]
```
"\bstyle\b\W*\=.*bexpression\b\W*\("
```
Isn't it should be
```
"\bstyle\b\W*\=.*\bexpression\b\W*\("
```

**Comment by csanders-git** [comment]
Looks like it lost the \b somewhere along the way... Good catch!
For those at home, this only affects CRS 2.x, 3.x relies on LibInjection
I just pushed a fix right now. Thank you!

**Comment by p0pr0ck5** [comment]
This looks like it wasn't fixed entirely, 981136 still checks for '@pm bexpression'.

**Comment by csanders-git** [comment]
Confirmed that issue

**Comment by csanders-git** [comment]
Thanks @p0pr0ck5, I pushed that change This should be fixed now.
