### ISSUE TITLE
Possible bypass using GET/HEAD with Transfer-Encoding

### ISSUE THREAD

**Issue by fgsch** [SpiderLabs/owasp-modsecurity-crs#909]
As per https://tools.ietf.org/html/rfc7230#page-28:

```
   The presence of a message body in a request is signaled by a
   Content-Length or Transfer-Encoding header field.  Request message
   framing is independent of method semantics, even if the method does
   not define any use for a message body.
```

Rule 920170 deals with Content-Length. We should handle T-E as well.

**Comment by spartantri** [comment]
see #905 it addresses T-E

**Comment by fgsch** [comment]
Thanks. I've checked and AFAICT this is not addressed in #905 .
Please correct me if I'm wrong.

**Comment by spartantri** [comment]
You're right, now I remember that I leaved that part out since still not agreed if having bodies in get and head is allowed by CRS or not, to me it shouldn't and any `GET|HEAD` request using `content-length` or `Transfer-Encoding` should be rejected at `PL1`, it is basic stuff, and it those are easy `phase:1` checks

**Comment by dune73** [comment]
+1 to the PL1. On a 2nd thought, it is also very rare and would it actually mean a problem or simply lead to a 400 on any application server?

**Comment by fgsch** [comment]
This is exactly what #909 does.

That said, Elasticsearch is one of those apps showing this behaviour (ref. https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-query-string-query.html).

In all fairness the RFCs do not prohibit this, it's left undefined, but since it's already done for Content-Length I don't think it should be any different for Transfer-Encoding.

**Comment by spartantri** [comment]
I seen that in several other apps, it's weird, the RFC says should not must so CRS must enforce the best behavior and all weird or gray areas must be handled as exceptions.

Same as for wordpress, where there is a list of known exceptions there should be another for popular apps as elasticsearch. If this happens to be very frequent then the checks for weird non RFC compliant stuff could be moved to PL2.

What do you think?

**Comment by fgsch** [comment]
That's not what the RFC says:

```
   A payload within a GET request message has no defined semantics;
   sending a payload body on a GET request might cause some existing
   implementations to reject the request.
```

Same for HEAD.  So it's not invalid, albeit not common.

IMO we should add this as it is or move 920170 and add this in a different PL.

**Comment by fgsch** [comment]
PR merged. 

Keeping this open until after the tests are added to the regression suite.

**Comment by fgsch** [comment]
To be continued in the right repo.
